
mach-mem-y		:= memcpy.o copy_from_user.o copy_to_user.o copy_page.o memmove.o

obj-$(CONFIG_HAS_MACH_MEMUTILS) += $(mach-mem-y)

KBUILD_CFLAGS += -fno-graphite-identity -fno-graphite -fno-loop-block -fno-loop-strip-mine -fno-tree-loop-distribution -fno-tree-loop-linear
